Nop.Plugin.Api/Areas/Admin/Controllers/ApiAdminController.cs
using Microsoft.AspNetCore.Mvc;
using Nop.Core;
using Nop.Plugin.Api.Areas.Admin.Models;
using Nop.Plugin.Api.Domain;
using Nop.Plugin.Api.MappingExtensions;
using Nop.Services.Configuration;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Messages;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Plugin.Api.Areas.Admin.Controllers
{
    [AuthorizeAdmin]
    [Area(AreaNames.ADMIN)]
    public class ApiAdminController : BasePluginController
    {
        private readonly ICustomerActivityService _customerActivityService;
        private readonly ILocalizationService _localizationService;
        private readonly INotificationService _notificationService;
        private readonly ISettingService _settingService;
        private readonly IStoreContext _storeContext;

        public ApiAdminController(
            IStoreContext storeContext,
            ISettingService settingService,
            ICustomerActivityService customerActivityService,
            ILocalizationService localizationService,
            INotificationService notificationService)
        {
            _storeContext = storeContext;
            _settingService = settingService;
            _customerActivityService = customerActivityService;
            _localizationService = localizationService;
            _notificationService = notificationService;
        }

        [HttpGet]
        public async Task<IActionResult> Settings()
        {
            var storeScope = await _storeContext.GetActiveStoreScopeConfigurationAsync();
            var apiSettings = await _settingService.LoadSettingAsync<ApiSettings>(storeScope);
            var model = apiSettings.ToModel();

            // Store Settings
            model.ActiveStoreScopeConfiguration = storeScope;

            if (model.EnableApi_OverrideForStore || storeScope == 0)
            {
                await _settingService.SaveSettingAsync(apiSettings, x => x.EnableApi, storeScope, false);
            }
            if (model.TokenExpiryInDays_OverrideForStore || storeScope == 0)
            {
                await _settingService.SaveSettingAsync(apiSettings, x => x.TokenExpiryInDays, storeScope, false);
            }

            //now clear settings cache
            await _settingService.ClearCacheAsync();

            return View($"~/Plugins/Nop.Plugin.Api/Areas/Admin/Views/ApiAdmin/Settings.cshtml", model);
        }

        [HttpPost]
        public async Task<IActionResult> Settings(ConfigurationModel model)
        {
            //load settings for a chosen store scope
            var storeScope = await _storeContext.GetActiveStoreScopeConfigurationAsync();

            var settings = model.ToEntity();

            /* We do not clear cache after each setting update.
            * This behavior can increase performance because cached settings will not be cleared 
            * and loaded from database after each update */

            if (model.EnableApi_OverrideForStore || storeScope == 0)
            {
                await _settingService.SaveSettingAsync(settings, x => x.EnableApi, storeScope, false);
            }
            if (model.TokenExpiryInDays_OverrideForStore || storeScope == 0)
            {
                await _settingService.SaveSettingAsync(settings, x => x.TokenExpiryInDays, storeScope, false);
            }

            //now clear settings cache
            await _settingService.ClearCacheAsync();

            await _customerActivityService.InsertActivityAsync("EditApiSettings", "Edit Api Settings");

            _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Admin.Plugins.Saved"));

            return View($"~/Plugins/Nop.Plugin.Api/Areas/Admin/Views/ApiAdmin/Settings.cshtml", model);
        }
    }
}

Nop.Plugin.Api/Areas/Admin/Views/ApiAdmin/Settings.cshtml
@using Nop.Plugin.Api.Infrastructure
@model Nop.Plugin.Api.Areas.Admin.Models.ConfigurationModel

@{
    Layout = "_ConfigurePlugin";

    //page title
    //ViewBag.Title = T("Plugins.Api.Admin.Page.Settings.Title").Text;

    //active menu item (system name)
    //Html.SetActiveMenuItemSystemName("Api-Settings-Menu");
}

<form asp-controller="ApiAdmin" asp-action="Settings" method="post">
    @Html.AntiForgeryToken()

    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Plugins.Api.Admin.Page.Settings.Title")
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
        </div>
    </div>

    <div class="content">
        <div class="form-horizontal">
            @await Component.InvokeAsync("StoreScopeConfiguration")
            @Html.ValidationSummary(false)
            <div class="panel-group">

                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="form-group">
                            <div class="col-md-3">
                                <nop-override-store-checkbox asp-for="EnableApi_OverrideForStore" asp-input="EnableApi" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                                <nop-label asp-for="EnableApi" />
                            </div>
                            <div class="col-md-9">
                                <nop-editor asp-for="EnableApi" />
                                <span asp-validation-for="EnableApi"></span>
                            </div>
                        </div>
                        <div class="form-group advanced-setting">
                            <div class="col-md-3">
                                <nop-override-store-checkbox asp-for="TokenExpiryInDays_OverrideForStore" asp-input="TokenExpiryInDays" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                                <nop-label asp-for="TokenExpiryInDays" />
                            </div>
                            <div class="col-md-9">
                                <nop-editor asp-for="TokenExpiryInDays" />
                                <span asp-validation-for="TokenExpiryInDays"></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>